{"name":"Local: fix_bug","url":"c:\\Users\\84395\\Documents\\GitHub\\Python-PTIT\\fix_bug.py","tests":[{"id":1688902886600,"input":"1111\n1111\n0000\n0000\n0000\n0000\n1111\n1111","output":""}],"interactive":false,"memoryLimit":1024,"timeLimit":3000,"srcPath":"c:\\Users\\84395\\Documents\\GitHub\\Python-PTIT\\fix_bug.py","group":"local","local":true}